AppBundle\Entity\Appartements:
    type: entity
    table: appartements
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            fixed: false
        adresse1:
            type: string
            nullable: false
            length: 255
            fixed: false
        adresse2:
            type: string
            nullable: false
            length: 255
            fixed: false
        cp:
            type: integer
            nullable: false
            unsigned: false
        ville:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
